package mov;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class MovCond {
  interface Visitor<R> {
    R visitKindCMovCond(KindC movcond);
  }
  static class KindC extends MovCond {
    KindC(Kind kind, Query query, String str) {
      this.kind = kind;
      this.query = query;
      this.str = str;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitKindCMovCond(this);
    }

    final Kind kind;
    final Query query;
    final String str;

    @Override
    public String toString() {
      return "KindC(" + kind + ", " + query + ", " + str + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
