package mov;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class MovExpr {
  interface Visitor<R> {
    R visitWhereMovExpr(Where movexpr);
    R visitWithoutMovExpr(Without movexpr);
  }
  static class Where extends MovExpr {
    Where(MovToken keyword, MovExpr condition) {
      this.keyword = keyword;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWhereMovExpr(this);
    }

    final MovToken keyword;
    final MovExpr condition;

    @Override
    public String toString() {
      return "Where(" + keyword + ", " + condition + ")";
    }
  }
  static class Without extends MovExpr {
    Without(MovToken keyword, MovExpr condition) {
      this.keyword = keyword;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWithoutMovExpr(this);
    }

    final MovToken keyword;
    final MovExpr condition;

    @Override
    public String toString() {
      return "Without(" + keyword + ", " + condition + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
