package mov;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class MovExpr {
  interface Visitor<R> {
    R visitWhereMovExpr(Where movexpr);
    R visitWithoutEMovExpr(WithoutE movexpr);
    R visitHaveEMovExpr(HaveE movexpr);
    R visitSayEMovExpr(SayE movexpr);
  }
  static class Where extends MovExpr {
    Where(MovToken keyword, MovExpr condition) {
      this.keyword = keyword;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWhereMovExpr(this);
    }

    final MovToken keyword;
    final MovExpr condition;

    @Override
    public String toString() {
      return "Where(" + keyword + ", " + condition + ")";
    }
  }
  static class WithoutE extends MovExpr {
    WithoutE(MovToken keyword, MovExpr condition) {
      this.keyword = keyword;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWithoutEMovExpr(this);
    }

    final MovToken keyword;
    final MovExpr condition;

    @Override
    public String toString() {
      return "WithoutE(" + keyword + ", " + condition + ")";
    }
  }
  static class HaveE extends MovExpr {
    HaveE(MovToken identifier, MovStmt statement) {
      this.identifier = identifier;
      this.statement = statement;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitHaveEMovExpr(this);
    }

    final MovToken identifier;
    final MovStmt statement;

    @Override
    public String toString() {
      return "HaveE(" + identifier + ", " + statement + ")";
    }
  }
  static class SayE extends MovExpr {
    SayE(MovToken identifier, MovToken ratsum, MovToken numstr) {
      this.identifier = identifier;
      this.ratsum = ratsum;
      this.numstr = numstr;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitSayEMovExpr(this);
    }

    final MovToken identifier;
    final MovToken ratsum;
    final MovToken numstr;

    @Override
    public String toString() {
      return "SayE(" + identifier + ", " + ratsum + ", " + numstr + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
