package mov;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class MovStmt {
  interface Visitor<R> {
    R visitFindSMovStmt(FindS movstmt);
    R visitHaveSMovStmt(HaveS movstmt);
    R visitSaySMovStmt(SayS movstmt);
    R visitWriteSMovStmt(WriteS movstmt);
  }
  static class FindS extends MovStmt {
    FindS(Kind kind, Query query, MovToken identifier, Condition condition) {
      this.kind = kind;
      this.query = query;
      this.identifier = identifier;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitFindSMovStmt(this);
    }

    final Kind kind;
    final Query query;
    final MovToken identifier;
    final Condition condition;

    @Override
    public String toString() {
      return "FindS(" + kind + ", " + query + ", " + identifier + ", " + condition + ")";
    }
  }
  static class HaveS extends MovStmt {
    HaveS(Kind kind, MovToken identifier, Condition condition) {
      this.kind = kind;
      this.identifier = identifier;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitHaveSMovStmt(this);
    }

    final Kind kind;
    final MovToken identifier;
    final Condition condition;

    @Override
    public String toString() {
      return "HaveS(" + kind + ", " + identifier + ", " + condition + ")";
    }
  }
  static class SayS extends MovStmt {
    SayS(MovToken identifier, MovToken ratsum, MovToken numstr) {
      this.identifier = identifier;
      this.ratsum = ratsum;
      this.numstr = numstr;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitSaySMovStmt(this);
    }

    final MovToken identifier;
    final MovToken ratsum;
    final MovToken numstr;

    @Override
    public String toString() {
      return "SayS(" + identifier + ", " + ratsum + ", " + numstr + ")";
    }
  }
  static class WriteS extends MovStmt {
    WriteS(Kind kind, Query query, MovToken identifier, Condition condition) {
      this.kind = kind;
      this.query = query;
      this.identifier = identifier;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWriteSMovStmt(this);
    }

    final Kind kind;
    final Query query;
    final MovToken identifier;
    final Condition condition;

    @Override
    public String toString() {
      return "WriteS(" + kind + ", " + query + ", " + identifier + ", " + condition + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
