package mov;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

abstract class MovStmt {
  interface Visitor<R> {
    R visitFindSMovStmt(FindS movstmt);
    R visitWriteSMovStmt(WriteS movstmt);
    R visitExpressionStmt(Expression movstmt);
  }

  public static class Expression extends MovStmt {
    public final MovExpr expression;
    public Expression(MovExpr expression) {
      this.expression = expression;
    }
    
    @Override
    <R> R accept(Visitor<R> visitor) {
        return visitor.visitExpressionStmt(this);
    }

    @Override
    public String toString() {
      return "Expression(" + expression + ")";
    }
  }

  static class FindS extends MovStmt {
    FindS(Kind kind, Query query, MovToken identifier, MovCond condition) {
      this.kind = kind;
      this.query = query;
      this.identifier = identifier;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitFindSMovStmt(this);
    }

    final Kind kind;
    final Query query;
    final MovToken identifier;
    final MovCond condition;

    @Override
    public String toString() {
      return "FindS(" + kind + ", " + query + ", " + identifier + ", " + condition + ")";
    }
  }
 
  static class WriteS extends MovStmt {
    WriteS(Kind kind, Query query, MovToken identifier, MovCond condition) {
      this.kind = kind;
      this.query = query;
      this.identifier = identifier;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWriteSMovStmt(this);
    }

    final Kind kind;
    final Query query;
    final MovToken identifier;
    final MovCond condition;

    @Override
    public String toString() {
      return "WriteS(" + kind + ", " + query + ", " + identifier + ", " + condition + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}